os: linux
dist: xenial
language: node_js
node_js:
  - "12"
env:
  - NODE_ENV=development CLOUDSDK_CORE_PROJECT=personal-165615 CLOUDSDK_COMPUTE_ZONE=us-central1-a
branches:
  only:
    - master
    - develop
before_install:
  # update yarn and npm
  - npm i npm -g
  - npm i yarn -g
  - echo "npm $(npm -v)" && echo "yarn $(yarn -v)"
  # authenticate the registry
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
install:
  - yarn
stages:
  - name: release
    if: type = pull_request OR branch = master
  - name: publish
    if: NOT (type IN (pull_request, api)) AND branch = master
jobs:
  include:
    - stage: release
      script:
        # - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn test; fi
        - npm run autorelease -- --expanded
    - stage: publish
      services:
        - docker
      install:
        - source .ci/gcloud-setup.sh
        - yarn
      script:
        - docker build -t tmp_build .
        - docker tag tmp_build gcr.io/personal-165615/tjme:latest
        - docker push gcr.io/personal-165615/tjme:latest
cache:
  yarn: true
  directories:
    - "$HOME/google-cloud-sdk"
