sudo: false
language: node_js
node_js:
  - '5'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm i -g npm@latest
before_script:
  - npm run lint
script:
  - npm run build
after_success:
  - npm run semantic-release
branches:
  only:
    - "master"
