apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tjme
  namespace: <%= $.namespace %>
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: tjme
        app: tjme
    spec:
      containers:
      - image: mrgalaxy/tjme:latest
        name: tjme
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tjme
  namespace: <%= $.namespace %>
  labels:
    name: tjme
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    name: tjme
